"""Create models and associations

Revision ID: 3e8b71da0089
Revises:
Create Date: 2025-09-27 14:01:01.815599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e8b71da0089"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("height", sa.String(length=10), nullable=True),
        sa.Column("mass", sa.String(length=10), nullable=True),
        sa.Column("hair_color", sa.String(length=50), nullable=True),
        sa.Column("skin_color", sa.String(length=50), nullable=True),
        sa.Column("eye_color", sa.String(length=50), nullable=True),
        sa.Column("birth_year", sa.String(length=20), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("edited", sa.DateTime(), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "films",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("opening_crawl", sa.Text(), nullable=False),
        sa.Column("director", sa.String(length=100), nullable=False),
        sa.Column("producer", sa.String(length=200), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("edited", sa.DateTime(), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "starships",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("manufacturer", sa.String(length=100), nullable=False),
        sa.Column("cost_in_credits", sa.String(length=20), nullable=True),
        sa.Column("length", sa.String(length=20), nullable=True),
        sa.Column("max_atmosphering_speed", sa.String(length=20), nullable=True),
        sa.Column("crew", sa.String(length=50), nullable=True),
        sa.Column("passengers", sa.String(length=20), nullable=True),
        sa.Column("cargo_capacity", sa.String(length=20), nullable=True),
        sa.Column("consumables", sa.String(length=50), nullable=True),
        sa.Column("hyperdrive_rating", sa.String(length=10), nullable=True),
        sa.Column("mglt", sa.String(length=10), nullable=True),
        sa.Column("starship_class", sa.String(length=50), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("edited", sa.DateTime(), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "character_films",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["films.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "film_id"),
    )
    op.create_table(
        "character_starships",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("starship_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["starship_id"],
            ["starships.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "starship_id"),
    )
    op.create_table(
        "film_starships",
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("starship_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["films.id"],
        ),
        sa.ForeignKeyConstraint(
            ["starship_id"],
            ["starships.id"],
        ),
        sa.PrimaryKeyConstraint("film_id", "starship_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("film_starships")
    op.drop_table("character_starships")
    op.drop_table("character_films")
    op.drop_table("starships")
    op.drop_table("films")
    op.drop_table("characters")
    # ### end Alembic commands ###
